pipeline {
  agent {
    kubernetes {
      yamlFile 'ci/kubernetes.yaml'
    }
  }

  options {
    timeout(time: 20, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  stages {
    stage('Build') {
      steps {
        container('maven') {
          mvn goal: 'clean verify -P sign', dependencies: 'dependencies/maven.deps'
          archiveArtifacts 'java/bundles/org.eclipse.set.model.releng.repository/target/*.zip'
        }
      }
    }

    stage('Process Licenses') {
      steps {
        container('maven') {
          collectDependencies()
        }
      }
    }

    stage('Deploy') {
      when {
        anyOf {
          buildingTag()
          branch 'main'
          branch pattern: 'release/[0-9.]+', comparator: 'REGEXP'
        }
      }

      steps {
        deployP2Site name: 'model', branch: BRANCH_NAME, path: 'java/bundles/org.eclipse.set.model.releng.repository/target/repository'
      }
    }
  }

  post {
    always {
      // Publish JUnit test result
      junit testResults: 'java/bundles/*/target/surefire-reports/*.xml', allowEmptyResults: true
      handleIssues()
    }
  }
}
