name: Create Release Tag
    
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version. Format: <major>.<minor>.<patch>(.<tag>)'
        required: true

jobs:
  release-tag:
    uses: eclipse-set/build/.github/workflows/release-tag.yml@main
    permissions:
      contents: write
    with:
      version: ${{ inputs.version }}
      target: "java/org.eclipse.set.model.releng.target/org.eclipse.set.model.releng.target.target"
