name: Create Release Branch
    
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version. Format: <major>.<minor>'
        required: true

jobs:
  release-branch:
    uses: eclipse-set/build/.github/workflows/release-branch.yml@main
    permissions:
      contents: write
    with:
      version: ${{ inputs.version }}
      target: "java/org.eclipse.set.model.releng.target/org.eclipse.set.model.releng.target.target"
